<?php
/**
 * Fill this out, should be pretty easy. Notice the commas also.
 * Also, the title association is NOT used in the development. They are
 * just here to show you which streams is which.. helps a lot for own3D
 */

//username => title
$twitch = array(
	"neodota" => "NEO DotA",
	"fivestream" => "5-s",
	"fiercetv" => "Fierce",
	"asrmatt" => "asrmatt",
	"nomstaiters" => "taitertot",
	"forbstream" => "MrForbs",
	"aliastar" => "alia",
	"ryuuboruzz" => "ryuuboruzz",
	"bulbasaurrrrrr" => "BuLba-SaUr",
	"imasheepsux" => "ima_sheep(sux)",
	"vtgenocide" => "GenocideRun",
	"chualon" => "ricefarmer301",
	"kiddie22" => "Kiddie",
	"thejizzla06" => "jizz1e",
	"tidesoftime" => "TidesofTime",
	"draskyll" => "draskyl",
	"huberdozer" => "huber",
	"s00thslayer" => "Soothsayer",
	"chedo1" => "ChEDo",
	"dotademon" => "DeMoN",
	"gamingwithgizmoh" => "Gizmoh",
	"inkcjr" => "inK",
	"zigrakil" => "Zigrakil",
	"isueyou2" => "Last4One",
	"mikeydota" => "Mikey",
	"lavicz" => "lavicz",
	"selfishHEHJK" => "selfishHEHJK",
	"khazers" => "khazers",
	"leoj151" => "Leoj",
	"theorigins" => "ritsulove",
	"grandgrant" => "GranDGranT",
	"feardarkness" => "Fear",
	"accSlight" => "Slight",
	"ggnetcharms" => "GGnetCharms",
	"thepremierleague" => "The Premier League",
	"514lunch" => "Tryout",
	"sleisel" => "Sleisel",
	"dotahero" => "hero",
	"itsgosu_dota2" => "It's GoSu",
	"coljah" => "jah",
	"blitzdota" => "blitz",
	"inori92" => "inori",
	"dota2peru" => "xesk1e",
	"ggnetpurge" => "Purge",
	"comeWithMe" => "ComeWithMe",
	"whatiship" => "WhatIsHip",
	"Sing_sing" => "WehSing",
	"mayafreak" => "JESSICA_JUNG",
	"Maelk" => "Maelk",
	"trancedota" => "Trance",
	"akirixx" => "Akiri",
	"trNsHellFire" => "HellFire69",
	"korokodile" => "Korok",
	"f4ldota" => "JokeZ",
	"dchow10" => "dchow",
	"insom23" => "Insomniac",
	"publicplayer" => "publicenemy",
	"font_" => "marcbase",
	"dotanewera" => "newera",
	"splinter_ep" => "Splinter",
	"spritzer555xfire1" => "Haxity",
	"LuminousInverse" => "Luminous",
	"coljeyo" => "Jeyo",
	"ggnetgeno" => "Geno",
	"colixmike88" => "ixmike88",
	"riskdotastream" => "Risk Player",
	"fuzzystoic" => "FuzzyBear",
	"inphinity_" => "inphinity",
	"spitwad" => "Spit-wad",
	"skullice" => "Skull.IcE",
	"madvillain_" => "Demise",
	"arteezy" => "ArtEEzY",
	"versuta" => "Versuta",
	"sneyking" => "sneyking",
	"eternalenvyy" => "eternalenvyy",
	"battlechicago" => "battlechicago",
);

//channel id => title
$own3D = array (
	266057 => 'ECAL.tv',
	10588 => 'TobiWanKenobi',
	106735 => 'Dendi',
	179879 => 'syndereN',
	73096 => 'Loda',
	100962 => 'LighTofHeaveN',
	117967 => 'LINK',
	10063 => 'Nemesis',
	203459 => 'Tanari',
	278187 => 'BRAXBRAXBRAX',
	198601 => 'DotaCinema',
	346 => 'iCCupTV',
	46733 => 'jauted',
	62729 => 'GosuProGamer',
);

?>